### PR TITLE
Xunit2 and compare3

### PR DESCRIPTION
**Pull request by alexeyzimarev**

### CODE REVIEW

**Comment by yreynhout** [comment]
Looking good, will merge soon.

**Comment by alexeyzimarev** [comment]
May be instead of migrating to Xunit2, I can make a separate project for Xunit2, leaving possibility to use Xunit?

**Comment by yreynhout** [comment]
Maybe, but then again, how many people are using Xunit support?

**Comment by alexeyzimarev** [comment]
No one can answer that but from my observations Xunit is not less popular than Xunit. Microsoft uses Xunit, expect the crowd to follow.

**Comment by yreynhout** [comment]
Knock yourself out :-)

**Comment by alexeyzimarev** [comment]
Well, I only use Xunit (eventually Xunit2 now) just because I like it

**Comment by yreynhout** [comment]
All dependencies have been updated. Closing this one.

**Pull request closed without merging**
